name: Release

on:
  release:
    types: [published]

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch: [amd64, arm64]

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build binary
      env:
        GOOS: linux
        GOARCH: ${{ matrix.goarch }}
      run: |
        OUTPUT_NAME=ngcli-linux-${{ matrix.goarch }}
        go build -o ${OUTPUT_NAME} .

    - name: Create archive
      run: |
        OUTPUT_NAME=ngcli-linux-${{ matrix.goarch }}
        tar -czf ${OUTPUT_NAME}.tar.gz ${OUTPUT_NAME}

    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./ngcli-linux-${{ matrix.goarch }}.tar.gz
        asset_name: ngcli-linux-${{ matrix.goarch }}.tar.gz
        asset_content_type: application/gzip